from __future__ import print_function

# For Python 2.7
# you need to have request installed on your computer
# pip install requests

#Ares documentation is available here:
#  http://127.0.0.1:5000/reports/doc
#[This documentation is autogenerated from the script comments]

import requests
import json


reportName = 'Youpi'
projectLocalPath = r'E:\GitHub\Ares\localtests\%s' % reportName

# Possible category of reports
# report - For a bespoke python report which will have a defined display
# ajax - For a python service. This will not display anything but return dictionaries
# configuration - For static configuration files. Extension .json
# js - For javascript templates (like text files)
filenames = [('Test.py', 'report'),
             ]

# The Url to be used in order to create the environments in Ares
# This will allow the use of scripts instead of the web interface
serverPath = 'http://127.0.0.1:5000'
postUrlDeploy = r'%s/reports/upload/%s/%s'
postUrlCreate = r'%s/reports/create/env' % serverPath
postUrlFolderCreate = r'%s/reports/folder/create' % serverPath
postUrlScriptVersion = r"%s/reports/ares/version" % serverPath
withEnvCreation = False

def uploadFile(filename, fileType):
  """ Upload a file on the server """
  if withEnvCreation:
    response = requests.post(postUrlCreate, {'REPORT_NAME': reportName})
    if response.status_code == 500:
      print("########################################")
      print("Problem in the environment creation")
      print("########################################")
      print(response.text)

  files = {'file': open(r"%s\%s" % (projectLocalPath, filename))}
  response = requests.post(postUrlDeploy % (serverPath, fileType, reportName), files=files)
  if response.status_code == 500:
    print("########################################")
    print("The environment is potentially missing")
    print("########################################")
    print(response.text)

def createFolders(folders):
  """ Create a folder on the server """
  response = requests.post(postUrlFolderCreate, {'REPORT_NAME': reportName, 'FOLDERS': "/".join(folders)})
  print(response)

def getPackageVersion():
  """  Check the version of the files on the server to ensure that the framework runs with the last version
  this service will return the last modification time and the size from [stat.st_mtime, stat.st_size]

    stat = os.stat(os.path.join(aresModulePath, pyFile))
  """
  # TODO add the comparison in the RIskLab shared folder
  response = requests.post(postUrlScriptVersion)
  print(json.loads(response.text))

#createFolders(['aa', 'bb'])
for filename, fileType in filenames:
  uploadFile(filename, fileType)
