from __future__ import print_function

# For Python 2.7
# you need to have request installed on your computer
# pip install requests

#Ares documentation is available here:
#  http://127.0.0.1:5000/reports/doc
#[This documentation is autogenerated from the script comments]

import requests
import json
import os

reportName = 'HelloWorld'
projectLocalPath = os.path.join(os.getcwd(), reportName)
filename = 'HelloWorld.py'

# The Url to be used in order to create the environments in Ares
# This will allow the use of scripts instead of the web interface
serverPath = 'http://127.0.0.1:5000'
postUrlDeploy = r'%s/reports/upload/%s' % (serverPath, reportName)
postUrlCreate = r'%s/reports/create/env' % serverPath
postUrlFolderCreate = r'%s/reports/folder/create' % serverPath
postUrlScriptVersion = r"%s/reports/ares/version" % serverPath
withEnvCreation = True

def uploadFile(filename):
  """ Upload a file on the server """
  files = {'file': open(r"%s\%s" % (projectLocalPath, filename))}
  response = requests.post(postUrlDeploy, files=files)
  if response.status_code == 500:
    print("########################################")
    print("The environment is potentially missing")
    print("########################################")
    if withEnvCreation:
      response = requests.post(postUrlCreate, {'REPORT': reportName})
      files = {'file': open(r"%s\%s" % (projectLocalPath, filename))}
      response = requests.post(postUrlDeploy, files=files)
      print(response)

def createFolders(folders):
  """ Create a folder on the server """
  response = requests.post(postUrlFolderCreate, {'REPORT_NAME': reportName, 'FOLDERS': "/".join(folders)})
  print(response)

def getPackageVersion():
  """  Check the version of the files on the server to ensure that the framework runs with the last version
  this service will return the last modification time and the size from [stat.st_mtime, stat.st_size]

    stat = os.stat(os.path.join(aresModulePath, pyFile))
  """
  # TODO add the comparison in the RIskLab shared folder
  response = requests.post(postUrlScriptVersion)
  print(json.loads(response.text))

#createFolders(['aa', 'bb'])
uploadFile(filename)