"""

"""

DOWNLOAD = None

def report(aresObj):
  """
  """
  aresObj.title("A simple Python Framework")
  aresObj.paragraph("This Lab is only composed by simple and basic python modules. It will benefit from Flask and Jinja frameworks"
                    " to bring new features. Within this Lab you will be able to reuse the different services that your IT"
                    " team will expose to you and you will be able to test them together in a isolated manner."
                    "The Lab will help you to {0} the development cycle in your company and to {1} the requests to the"
                    "support team for more clarity", htmlComp=[aresObj.text("reduce", cssAttr={'font-weight': 'bold', 'color': '#398438', 'font-size': '23px'}),
                                                               aresObj.text("stop", cssAttr={'font-weight': 'bold', 'color': '#398438', 'font-size': '23px'})
                                                               ])

  aresObj.title4("Better understanding of the system")
  content = aresObj.paragraph("No hidden mapping anymore. You will be able to download some important source codes in order to"
                    "understand the results. No need to raise an incident to your support team, any opaque part of your "
                    "system can be converted to a downloadable framework for a better clarity")
  aresObj.row([content, aresObj.img('download_scripts.JPG')])

  aresObj.title4("Not need to learn other languages")
  content1 = aresObj.paragraph("The Python layer will be mainly the only one you will play with. All the Javascript and CSS"
                              " required parts to be web oriented will be automatically generated by the different wrapper classes."
                              " No need to be an expert in Javascript or CSS to use this platform but it is possible to see the result "
                              " produced by the different classes.")
  content2 = aresObj.paragraph("It is also possible to add your Javascript fragments in the code to customise it")
  fragment = aresObj.img('js_fragment.JPG', cssAttr={'margin-left': '15%'})
  aresObj.row([aresObj.col([content1, content2, fragment]), aresObj.col([aresObj.img('html_part.JPG'), aresObj.img('js_part.JPG')])])
  aresObj.title4("Better reactivity and Shared Dashboards")
  content1 = aresObj.paragraph("Dashboards can be downloaded, thus in case of input data change or important production issue"
                              " it is possible to adapt the official version of the framework to produce the reports on"
                              " time. Those simple but efficient changes can then be submitted to the IT team to be added"
                              " to the live version")
  content2 = aresObj.paragraph("Any new script and new reports will automatically create a url. Thus it will be easy to "
                              "test new reports, a change in methodology and to ask for a sign off. Reports generated can be"
                              " displayed on tablet or smartphones.")
  aresObj.row([aresObj.img('report_example.JPG', cssAttr={'margin-left': '10%'}), aresObj.col([content1, content2])])